/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaces;

import com.beans.Cliente;
import com.beans.Telefone;
import com.dao.ClienteFDao;
import com.dao.ClienteJDao;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class FrCliente extends javax.swing.JFrame {
    int cliente_t=0,id_fone1,id_fone2,id_fone3;
    /**
     * Creates new form FrCliente
     */
    public FrCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        URL url = this.getClass().getClassLoader().getResource("com/imagens/my-profile.png"); 
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);
        button_fisica.setSelected(true);
        cliente_t=0;
        painel1.setVisible(false);
        edit_btn.setEnabled(false);
        excluir_btn.setEnabled(false);
        cad_btn.setEnabled(true);
    }
    
    public void RetornaDados(Cliente c){
        
        switch (c.getTipo()) {
            case 1:
                button_fisica.setVisible(false);
                button_juridica.setVisible(false);   
                cliente_t=0;
                
                id_txt.setText(String.valueOf(c.getId()));
                nm_txt.setText(c.getNome());
                logr_txt.setText(c.getRua());
                num_txt.setText(String.valueOf(c.getNumero()));
                bai_txt.setText(c.getBairro());
                cid_txt.setText(c.getCidade());
                uf_txt.setText(c.getUf());
                cep_txt.setText(c.getCep());
                d_3.setText(c.getDt_nasc());
                d_1.setText(c.getRg());
                d_2.setText(c.getCpf());
                fixo_txt.setText(String.valueOf(c.getFone().getTelefones()[0]));
                id_fone1 = c.getFone().getIds()[0];
                cel_txt.setText(String.valueOf(c.getFone().getTelefones()[1]));
                id_fone2 = c.getFone().getIds()[1];
                con_txt.setText(String.valueOf(c.getFone().getTelefones()[2]));
                id_fone3 = c.getFone().getIds()[2];
                
            break;
            case 2:
                button_fisica.setVisible(false);
                button_juridica.setVisible(false);
                dado_1.setText("CNPJ");
                dado_3.setText("Razão Social");
                dado_2.setVisible(false);
                d_2.setVisible(false);
                cliente_t=1;
                
                id_txt.setText(String.valueOf(c.getId()));
                nm_txt.setText(c.getNome());
                logr_txt.setText(c.getRua());
                num_txt.setText(String.valueOf(c.getNumero()));
                bai_txt.setText(c.getBairro());
                cid_txt.setText(c.getCidade());
                uf_txt.setText(c.getUf());
                cep_txt.setText(c.getCep());
                d_3.setText(c.getRazao_s());
                d_1.setText(c.getCnpj());
                fixo_txt.setText(String.valueOf(c.getFone().getTelefones()[0]));
                id_fone1 = c.getFone().getIds()[0];
                cel_txt.setText(String.valueOf(c.getFone().getTelefones()[1]));
                id_fone2 = c.getFone().getIds()[1];
                con_txt.setText(String.valueOf(c.getFone().getTelefones()[2]));
                id_fone3 = c.getFone().getIds()[2];
                
            break;
            default:
                JOptionPane.showMessageDialog(null, "Opção Invalida!!!");
            }
        painel1.setVisible(true);
        edit_btn.setEnabled(true);
        excluir_btn.setEnabled(true);
        cad_btn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tipo_cliente = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        d_1 = new javax.swing.JTextField();
        dado_1 = new javax.swing.JLabel();
        d_2 = new javax.swing.JTextField();
        dado_2 = new javax.swing.JLabel();
        d_3 = new javax.swing.JTextField();
        dado_3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        logr_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        num_txt = new javax.swing.JTextField();
        bai_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cid_txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        uf_txt = new javax.swing.JTextField();
        cep_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        fixo_txt = new javax.swing.JTextField();
        cel_txt = new javax.swing.JTextField();
        con_txt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nm_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        excluir_btn = new javax.swing.JButton();
        cad_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        button_fisica = new javax.swing.JRadioButton();
        button_juridica = new javax.swing.JRadioButton();
        painel1 = new javax.swing.JPanel();
        id_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados"));

        dado_1.setText("RG");

        dado_2.setText("CPF");

        dado_3.setText("Data Nasc.");

        jLabel9.setText("Endereço");

        jLabel10.setText("Logradouro");

        jLabel11.setText("Numero");

        jLabel12.setText("Bairro");

        jLabel13.setText("Cidade");

        jLabel14.setText("UF");

        jLabel15.setText("CEP");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/Imagem/Preview_16x16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Telefone Fixo");

        jLabel17.setText("Telefone Celular");

        jLabel18.setText("Telefone Contato");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(bai_txt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(uf_txt)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(d_1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(dado_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(d_2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(dado_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d_3)
                                    .addComponent(dado_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cep_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(logr_txt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(num_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fixo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cel_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(con_txt)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dado_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dado_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dado_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(d_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(con_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cel_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fixo_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cep_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bai_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(uf_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cid_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nome"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nm_txt)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nm_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CLIENTE");

        excluir_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/Imagem/Delete_16x16.png"))); // NOI18N
        excluir_btn.setText("Excluir");
        excluir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_btnActionPerformed(evt);
            }
        });

        cad_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/Imagem/Add_16x16.png"))); // NOI18N
        cad_btn.setText("Cadastrar");
        cad_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_btnActionPerformed(evt);
            }
        });

        edit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/Imagem/Edit_16x16.png"))); // NOI18N
        edit_btn.setText("Editar");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        Tipo_cliente.add(button_fisica);
        button_fisica.setText("Pessoa Fisica");
        button_fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_fisicaActionPerformed(evt);
            }
        });

        Tipo_cliente.add(button_juridica);
        button_juridica.setText("Pessoa Juridica");
        button_juridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_juridicaActionPerformed(evt);
            }
        });

        painel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ID"));

        id_txt.setEditable(false);

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(id_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(excluir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cad_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(button_fisica)
                                .addGap(65, 65, 65)
                                .addComponent(button_juridica)
                                .addGap(87, 87, 87)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_fisica)
                    .addComponent(button_juridica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cad_btn)
                    .addComponent(edit_btn)
                    .addComponent(excluir_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_fisicaActionPerformed
        // TODO add your handling code here:
        dado_1.setText("RG");
        dado_3.setText("Data Nasc.");
        dado_2.setVisible(true);
        d_2.setVisible(true);
        cliente_t=0;
    }//GEN-LAST:event_button_fisicaActionPerformed

    private void button_juridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_juridicaActionPerformed
        // TODO add your handling code here:
        dado_1.setText("CNPJ");
        dado_3.setText("Razão Social");
        dado_2.setVisible(false);
        d_2.setVisible(false);
        cliente_t=1;
    }//GEN-LAST:event_button_juridicaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cad_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_btnActionPerformed
        // TODO add your handling code here:
        switch (cliente_t) {
            case 0:
                Cliente p = new Cliente();
                ClienteFDao f = new ClienteFDao();
                Telefone fone = new Telefone();

                p.setNome(nm_txt.getText());
                p.setRua(logr_txt.getText());
                p.setNumero(Integer.parseInt(num_txt.getText()));
                p.setBairro(bai_txt.getText());
                p.setCidade(cid_txt.getText());
                p.setUf(uf_txt.getText());
                p.setCep(cep_txt.getText());
                p.setRg(d_1.getText());
                p.setCpf(d_2.getText());
                p.setDt_nasc(d_3.getText());
                
                fone.getTelefones()[0] = Integer.parseInt(fixo_txt.getText());
                fone.getTelefones()[1] = Integer.parseInt(cel_txt.getText());
                fone.getTelefones()[2] = Integer.parseInt(con_txt.getText());
                
                p.setFone(fone);
                f.create(p);

                nm_txt.setText("");
                logr_txt.setText("");
                num_txt.setText("");
                bai_txt.setText("");
                cid_txt.setText("");
                uf_txt.setText("");
                cep_txt.setText("");
                d_1.setText("");
                d_2.setText("");
                d_3.setText("");
                fixo_txt.setText("");
                cel_txt.setText("");
                con_txt.setText("");
            break;
            case 1:
                Cliente j = new Cliente();
                ClienteJDao jr = new ClienteJDao();
                Telefone cel = new Telefone();

                j.setNome(nm_txt.getText());
                j.setRua(logr_txt.getText());
                j.setNumero(Integer.parseInt(num_txt.getText()));
                j.setBairro(bai_txt.getText());
                j.setCidade(cid_txt.getText());
                j.setUf(uf_txt.getText());
                j.setCep(cep_txt.getText());
                j.setCnpj(d_1.getText());
                j.setRazao_s(d_3.getText());
                
                cel.getTelefones()[0] = Integer.parseInt(fixo_txt.getText());
                cel.getTelefones()[1] = Integer.parseInt(cel_txt.getText());
                cel.getTelefones()[2] = Integer.parseInt(con_txt.getText());
                
                j.setFone(cel);
                jr.create(j);

                nm_txt.setText("");
                logr_txt.setText("");
                num_txt.setText("");
                bai_txt.setText("");
                cid_txt.setText("");
                uf_txt.setText("");
                cep_txt.setText("");
                d_1.setText("");
                d_2.setText("");
                d_3.setText("");
                fixo_txt.setText("");
                cel_txt.setText("");
                con_txt.setText("");
            break;
            default:
                JOptionPane.showMessageDialog(null, "Opção Invalida!!!");
        }
        
    }//GEN-LAST:event_cad_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
        switch (cliente_t) {
            case 0:
                Cliente p = new Cliente();
                ClienteFDao f = new ClienteFDao();
                Telefone fone = new Telefone();

                p.setId(Integer.parseInt(id_txt.getText()));
                p.setNome(nm_txt.getText());
                p.setRua(logr_txt.getText());
                p.setNumero(Integer.parseInt(num_txt.getText()));
                p.setBairro(bai_txt.getText());
                p.setCidade(cid_txt.getText());
                p.setUf(uf_txt.getText());
                p.setCep(cep_txt.getText());
                p.setRg(d_1.getText());
                p.setCpf(d_2.getText());
                p.setDt_nasc(d_3.getText());
                
                fone.getTelefones()[0] = Integer.parseInt(fixo_txt.getText());
                fone.getIds()[0] = id_fone1;
                fone.getTelefones()[1] = Integer.parseInt(cel_txt.getText());
                fone.getIds()[1] = id_fone2;
                fone.getTelefones()[2] = Integer.parseInt(con_txt.getText());
                fone.getIds()[2] = id_fone3;
                
                p.setFone(fone);
                f.update(p);

                id_txt.setText("");
                nm_txt.setText("");
                logr_txt.setText("");
                num_txt.setText("");
                bai_txt.setText("");
                cid_txt.setText("");
                uf_txt.setText("");
                cep_txt.setText("");
                d_1.setText("");
                d_2.setText("");
                d_3.setText("");
                fixo_txt.setText("");
                cel_txt.setText("");
                con_txt.setText("");
            break;
            case 1:
                Cliente j = new Cliente();
                ClienteJDao jr = new ClienteJDao();
                Telefone cel = new Telefone();

                j.setId(Integer.parseInt(id_txt.getText()));
                j.setNome(nm_txt.getText());
                j.setRua(logr_txt.getText());
                j.setNumero(Integer.parseInt(num_txt.getText()));
                j.setBairro(bai_txt.getText());
                j.setCidade(cid_txt.getText());
                j.setUf(uf_txt.getText());
                j.setCep(cep_txt.getText());
                j.setCnpj(d_1.getText());
                j.setRazao_s(d_3.getText());
                
                cel.getTelefones()[0] = Integer.parseInt(fixo_txt.getText());
                cel.getIds()[0] = id_fone1;
                cel.getTelefones()[1] = Integer.parseInt(cel_txt.getText());
                cel.getIds()[1] = id_fone2;
                cel.getTelefones()[2] = Integer.parseInt(con_txt.getText());
                cel.getIds()[2] = id_fone3;
                
                j.setFone(cel);
                jr.create(j);

                nm_txt.setText("");
                logr_txt.setText("");
                num_txt.setText("");
                bai_txt.setText("");
                cid_txt.setText("");
                uf_txt.setText("");
                cep_txt.setText("");
                d_1.setText("");
                d_2.setText("");
                d_3.setText("");
                fixo_txt.setText("");
                cel_txt.setText("");
                con_txt.setText("");
            break;
            default:
                JOptionPane.showMessageDialog(null, "Opção Invalida!!!");
        }
        painel1.setVisible(false);
        edit_btn.setEnabled(false);
        excluir_btn.setEnabled(false);
        cad_btn.setEnabled(true);
        
    }//GEN-LAST:event_edit_btnActionPerformed

    private void excluir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_btnActionPerformed
        // TODO add your handling code here:
        switch (cliente_t) {
            case 0:
                Cliente p = new Cliente();
                ClienteFDao f = new ClienteFDao();

                p.setId(Integer.parseInt(id_txt.getText()));
                f.delete(p);

                id_txt.setText("");
                nm_txt.setText("");
                logr_txt.setText("");
                num_txt.setText("");
                bai_txt.setText("");
                cid_txt.setText("");
                uf_txt.setText("");
                cep_txt.setText("");
                d_1.setText("");
                d_2.setText("");
                d_3.setText("");
                fixo_txt.setText("");
                cel_txt.setText("");
                con_txt.setText("");
            break;
            case 1:
                Cliente j = new Cliente();
                ClienteJDao jr = new ClienteJDao();

                j.setId(Integer.parseInt(id_txt.getText()));
                jr.delete(j);

                nm_txt.setText("");
                logr_txt.setText("");
                num_txt.setText("");
                bai_txt.setText("");
                cid_txt.setText("");
                uf_txt.setText("");
                cep_txt.setText("");
                d_1.setText("");
                d_2.setText("");
                d_3.setText("");
                fixo_txt.setText("");
                cel_txt.setText("");
                con_txt.setText("");
            break;
            default:
                JOptionPane.showMessageDialog(null, "Opção Invalida!!!");
        }
        painel1.setVisible(false);
        edit_btn.setEnabled(false);
        excluir_btn.setEnabled(false);
        cad_btn.setEnabled(true);
        
    
    }//GEN-LAST:event_excluir_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Tipo_cliente;
    private javax.swing.JTextField bai_txt;
    private javax.swing.JRadioButton button_fisica;
    private javax.swing.JRadioButton button_juridica;
    private javax.swing.JButton cad_btn;
    private javax.swing.JTextField cel_txt;
    private javax.swing.JTextField cep_txt;
    private javax.swing.JTextField cid_txt;
    private javax.swing.JTextField con_txt;
    private javax.swing.JTextField d_1;
    private javax.swing.JTextField d_2;
    private javax.swing.JTextField d_3;
    private javax.swing.JLabel dado_1;
    private javax.swing.JLabel dado_2;
    private javax.swing.JLabel dado_3;
    private javax.swing.JButton edit_btn;
    private javax.swing.JButton excluir_btn;
    private javax.swing.JTextField fixo_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField logr_txt;
    private javax.swing.JTextField nm_txt;
    private javax.swing.JTextField num_txt;
    private javax.swing.JPanel painel1;
    private javax.swing.JTextField uf_txt;
    // End of variables declaration//GEN-END:variables

}
