/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaces;

import com.beans.Cliente;
import com.beans.NotaFiscal;
import com.beans.Usuario;
import com.dao.ClienteFDao;
import com.dao.ClienteJDao;
import com.dao.NotaFiscalDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class FrEmprestimoCliente extends javax.swing.JFrame {
    int form, id_usuario;
    String nm_usuario;
    

    /**
     * Creates new form FrEmprestimoCliente
     */
    public FrEmprestimoCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        button_fisica.setSelected(true);
        this.Fisico_consulta();
        form=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cliente_grupo = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        text_t = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_t1 = new javax.swing.JTextField();
        button_fisica = new javax.swing.JRadioButton();
        button_juridica = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filtro"));

        jLabel1.setText("ID");

        jLabel2.setText("Nome");

        cliente_grupo.add(button_fisica);
        button_fisica.setText("Pessoa Fisica");
        button_fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_fisicaActionPerformed(evt);
            }
        });

        cliente_grupo.add(button_juridica);
        button_juridica.setText("Pessoa Juridica");
        button_juridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_juridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_t, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_t1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_fisica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_juridica, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(text_t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_fisica)
                    .addComponent(button_juridica))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void Retorna_usuario(Usuario p){
        id_usuario = p.getId();
        nm_usuario = p.getLogin();
    }
    
    private void button_fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_fisicaActionPerformed
        // TODO add your handling code here:
        form=0;
        this.Fisico_consulta();
    }//GEN-LAST:event_button_fisicaActionPerformed

    private void button_juridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_juridicaActionPerformed
        // TODO add your handling code here:
        form=1;
        this.Juridico_consulta();
    }//GEN-LAST:event_button_juridicaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jTable1.setDefaultEditor(Object.class, null);
        if(evt.getClickCount() == 2){
            int linha = jTable1.getSelectedRow();
            Cliente cli = new Cliente();
            FrEmprestimo em = new FrEmprestimo();
            Usuario u = new Usuario();
            NotaFiscal nf = new NotaFiscal();
            NotaFiscalDao nfD = new NotaFiscalDao();
            u.setId(id_usuario);
            u.setLogin(nm_usuario);
            
            switch (form) {
                case 0:
                    cli.setId((int) jTable1.getValueAt(linha, 0));
                    cli.setNome(jTable1.getValueAt(linha, 1).toString());
                    cli.setTipo(0);
                    em.setVisible(true);
                    em.RetornaDados(cli);
                break;
                case 1:
                    cli.setId((int) jTable1.getValueAt(linha, 0));
                    cli.setNome(jTable1.getValueAt(linha, 1).toString());
                    cli.setTipo(1);
                    em.setVisible(true);
                    em.RetornaDados(cli);
                break;
                default:
                    JOptionPane.showMessageDialog(null, "Opção Invalida!!!");
            }
            em.Retorna_usuario(u);
            this.dispose();
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    public void Juridico_consulta(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
                model.addColumn("ID");
                model.addColumn("Nome");
                model.addColumn("Logradouro");
                model.addColumn("Número");
                model.addColumn("Bairro");
                model.addColumn("Cidade");
                model.addColumn("UF");
                model.addColumn("cep");
                model.addColumn("Razão Social");
                model.addColumn("CNPJ");
                model.addColumn("Status");
        ClienteJDao pdao = new ClienteJDao();
        
        for (Cliente p : pdao.findAll()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getRua(),
                p.getNumero(),
                p.getBairro(),
                p.getCidade(),
                p.getUf(),
                p.getCep(),
                p.getRazao_s(),
                p.getCnpj(),
                p.getStatus()
            });
            jPanel1.setVisible(true);
        }
    }
    
    public void Fisico_consulta(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
                model.addColumn("ID");
                model.addColumn("Nome");
                model.addColumn("Logradouro");
                model.addColumn("Número");
                model.addColumn("Bairro");
                model.addColumn("Cidade");
                model.addColumn("UF");
                model.addColumn("cep");
                model.addColumn("Dt_nasc");
                model.addColumn("RG");
                model.addColumn("CPF");
                model.addColumn("Status");
        ClienteFDao pdao = new ClienteFDao();
        
        for (Cliente p : pdao.findAll()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getRua(),
                p.getNumero(),
                p.getBairro(),
                p.getCidade(),
                p.getUf(),
                p.getCep(),
                p.getDt_nasc(),
                p.getRg(),
                p.getCpf(),
                p.getStatus()
            });
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrEmprestimoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrEmprestimoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrEmprestimoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrEmprestimoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrEmprestimoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton button_fisica;
    private javax.swing.JRadioButton button_juridica;
    private javax.swing.ButtonGroup cliente_grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField text_t;
    private javax.swing.JTextField text_t1;
    // End of variables declaration//GEN-END:variables
}
