/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaces;

import com.beans.Acervo;
import com.beans.Autor;
import com.beans.Cargo;
import com.beans.Cliente;
import com.beans.Editora;
import com.beans.Funcionario;
import com.beans.Genero;
import com.beans.Telefone;
import com.beans.Usuario;
import com.conexao.ConnectionFactory;
import com.dao.AcervoDao;
import com.dao.ClienteFDao;
import com.dao.ClienteJDao;
import com.dao.FuncionarioDao;
import com.dao.UsuarioDao;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class FrPrincipal extends javax.swing.JFrame {
    Connection con;
    Statement st;
    int id_usuario;
    String nm_usuario;
    /**
     */
    public FrPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        URL url = this.getClass().getClassLoader().getResource("com/imagens/Text Document_16x16.png"); 
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);
        jPanel1.setVisible(false);
        txt_form.setVisible(false);
        con = ConnectionFactory.getConnection();
        /*URL url = this.getClass().getClassLoader().getResource("BR.jpg"); 
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbprincipal = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        text_t = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_t1 = new javax.swing.JTextField();
        txt_form = new javax.swing.JTextField();
        tipo_usuariolb = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        config_m = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        sair_m = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        cliente_m = new javax.swing.JMenuItem();
        func_m = new javax.swing.JMenuItem();
        acervo_m = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        usuario_m = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        cons_fis = new javax.swing.JMenuItem();
        cons_jur = new javax.swing.JMenuItem();
        cons_func = new javax.swing.JMenuItem();
        cons_acervo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        UsuarioC_m = new javax.swing.JMenuItem();
        Pedido_m = new javax.swing.JMenu();
        Emprestimo_m = new javax.swing.JMenuItem();
        rel_m = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        atualizacao_m = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("B²RAFS - BIBLIOTECA");

        tbprincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbprincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbprincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbprincipal);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filtro"));

        jLabel1.setText("ID");

        jLabel2.setText("Nome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_t, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_t1)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(text_t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jMenu2.setText("Arquivo");

        config_m.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagens/Settings_16x16.png"))); // NOI18N
        config_m.setText("Configuração");
        jMenu2.add(config_m);
        jMenu2.add(jSeparator1);

        sair_m.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagens/Log Out_16x16.png"))); // NOI18N
        sair_m.setText("Sair");
        sair_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_mActionPerformed(evt);
            }
        });
        jMenu2.add(sair_m);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cadastro");

        cliente_m.setText("Cliente");
        cliente_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliente_mActionPerformed(evt);
            }
        });
        jMenu3.add(cliente_m);

        func_m.setText("Funcionário");
        func_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                func_mActionPerformed(evt);
            }
        });
        jMenu3.add(func_m);

        acervo_m.setText("Acervo");
        acervo_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acervo_mActionPerformed(evt);
            }
        });
        jMenu3.add(acervo_m);
        jMenu3.add(jSeparator3);

        usuario_m.setText("Usuário");
        usuario_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuario_mActionPerformed(evt);
            }
        });
        jMenu3.add(usuario_m);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Consultar");

        jMenu7.setText("Cliente");

        cons_fis.setText("Fisico");
        cons_fis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_fisActionPerformed(evt);
            }
        });
        jMenu7.add(cons_fis);

        cons_jur.setText("Juridico");
        cons_jur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_jurActionPerformed(evt);
            }
        });
        jMenu7.add(cons_jur);

        jMenu5.add(jMenu7);

        cons_func.setText("Funcionário");
        cons_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_funcActionPerformed(evt);
            }
        });
        jMenu5.add(cons_func);

        cons_acervo.setText("Acervo");
        cons_acervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cons_acervoActionPerformed(evt);
            }
        });
        jMenu5.add(cons_acervo);
        jMenu5.add(jSeparator2);

        UsuarioC_m.setText("Usuário");
        UsuarioC_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioC_mActionPerformed(evt);
            }
        });
        jMenu5.add(UsuarioC_m);

        jMenuBar1.add(jMenu5);

        Pedido_m.setText("Pedido");

        Emprestimo_m.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagens/Forward_16x16.png"))); // NOI18N
        Emprestimo_m.setText("Emprestimo");
        Emprestimo_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emprestimo_mActionPerformed(evt);
            }
        });
        Pedido_m.add(Emprestimo_m);

        jMenuBar1.add(Pedido_m);

        rel_m.setText("Relatório");

        jMenuItem1.setText("Gerar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        rel_m.add(jMenuItem1);

        jMenuBar1.add(rel_m);

        jMenu6.setText("Ajuda");

        atualizacao_m.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagens/Calendar_16x16.png"))); // NOI18N
        atualizacao_m.setText("Atualização");
        atualizacao_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizacao_mActionPerformed(evt);
            }
        });
        jMenu6.add(atualizacao_m);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tipo_usuariolb, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_form, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_form)
                    .addComponent(tipo_usuariolb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sair_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_mActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_sair_mActionPerformed

    public void restricao(Usuario p){
        id_usuario = p.getId();
        nm_usuario = p.getLogin();
        
        switch (p.getTipo_usuario()) {
            case 0:
                tipo_usuariolb.setText("Usuário Adm");
                
            break;
            case 1:
                tipo_usuariolb.setText("Usuário Padrão");
                usuario_m.setEnabled(false);
                UsuarioC_m.setEnabled(false);
                rel_m.setEnabled(false);
                config_m.setEnabled(false);
                func_m.setEnabled(false);
            break;
            default:
                JOptionPane.showMessageDialog(null, "Opção Invalida!!!");
            }        
    }
    
    
    
    private void cliente_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliente_mActionPerformed
        // TODO add your handling code here:
        FrCliente frame = new FrCliente();
        frame.setVisible(true);
        
    }//GEN-LAST:event_cliente_mActionPerformed

    public void select_jtable(){
            int linha = tbprincipal.getSelectedRow();
            int form = Integer.parseInt(txt_form.getText());
            PreparedStatement stmt = null;
            ResultSet rs = null;
            
            switch (form) {
                case 1:
                    try {
                    Cliente cli = new Cliente();
                    FrCliente cliente = new FrCliente();
                    cli.setId((int) tbprincipal.getValueAt(linha, 0));
                    cli.setNome(tbprincipal.getValueAt(linha, 1).toString());
                    cli.setRua(tbprincipal.getValueAt(linha, 2).toString());
                    cli.setNumero((int) tbprincipal.getValueAt(linha, 3));
                    cli.setBairro(tbprincipal.getValueAt(linha, 4).toString());
                    cli.setCidade(tbprincipal.getValueAt(linha, 5).toString());
                    cli.setUf(tbprincipal.getValueAt(linha, 6).toString());
                    cli.setCep(tbprincipal.getValueAt(linha, 7).toString());
                    cli.setDt_nasc(tbprincipal.getValueAt(linha, 8).toString());
                    cli.setRg(tbprincipal.getValueAt(linha, 9).toString());
                    cli.setCpf(tbprincipal.getValueAt(linha, 10).toString());
                                        
                        stmt = con.prepareStatement("select Cliente.cd_cliente,Telefone_cliente.cd_fone_c,Telefone_cliente.numero "
                                + "from Cliente inner join Telefone_cliente on Cliente.cd_cliente = Telefone_cliente.cd_cliente "
                                + "where Cliente.cd_cliente = ?");
                        stmt.setInt(1, (int) tbprincipal.getValueAt(linha, 0));
                        rs = stmt.executeQuery();
                        
                        int i=0;
                        Telefone fone = new Telefone(); 
                        while(rs.next()){
                            fone.getIds()[i] = rs.getInt("cd_fone_c");
                            fone.getTelefones()[i] = rs.getInt("numero");
                            i+=1;
                        }
                    cli.setTipo(1);
                    cli.setFone(fone);
                    cliente.setVisible(true);
                    cliente.RetornaDados(cli);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Erro na busca! \n" + ex);
                    }
                break;
                case 2:
                    try {
                    Cliente cli = new Cliente();
                    FrCliente cliente = new FrCliente();
                    cli.setId((int) tbprincipal.getValueAt(linha, 0));
                    cli.setNome(tbprincipal.getValueAt(linha, 1).toString());
                    cli.setRua(tbprincipal.getValueAt(linha, 2).toString());
                    cli.setNumero((int) tbprincipal.getValueAt(linha, 3));
                    cli.setBairro(tbprincipal.getValueAt(linha, 4).toString());
                    cli.setCidade(tbprincipal.getValueAt(linha, 5).toString());
                    cli.setUf(tbprincipal.getValueAt(linha, 6).toString());
                    cli.setCep(tbprincipal.getValueAt(linha, 7).toString());
                    cli.setRazao_s(tbprincipal.getValueAt(linha, 8).toString());
                    cli.setCnpj(tbprincipal.getValueAt(linha, 9).toString());
                                        
                        stmt = con.prepareStatement("select Cliente.cd_cliente,Telefone_cliente.cd_fone_c,Telefone_cliente.numero "
                                + "from Cliente inner join Telefone_cliente on Cliente.cd_cliente = Telefone_cliente.cd_cliente "
                                + "where Cliente.cd_cliente = ?");
                        stmt.setInt(1, (int) tbprincipal.getValueAt(linha, 0));
                        rs = stmt.executeQuery();
                        
                        int i=0;
                        Telefone fone = new Telefone(); 
                        while(rs.next()){
                            fone.getIds()[i] = rs.getInt("cd_fone_c");
                            fone.getTelefones()[i] = rs.getInt("numero");
                            i+=1;
                        }
                    cli.setTipo(2);
                    cli.setFone(fone);
                    cliente.setVisible(true);
                    cliente.RetornaDados(cli);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Erro na busca! \n" + ex);
                    }
                break;
                case 3:
                    try {
                    Funcionario f = new Funcionario();
                    FrFuncionario func = new FrFuncionario();
                    Cargo ca = new Cargo();
                    f.setId((int) tbprincipal.getValueAt(linha, 0));
                    f.setNome(tbprincipal.getValueAt(linha, 1).toString());
                    f.setRua(tbprincipal.getValueAt(linha, 2).toString());
                    f.setNumero((int) tbprincipal.getValueAt(linha, 3));
                    f.setBairro(tbprincipal.getValueAt(linha, 4).toString());
                    f.setCidade(tbprincipal.getValueAt(linha, 5).toString());
                    f.setUf(tbprincipal.getValueAt(linha, 6).toString());
                    f.setCep(tbprincipal.getValueAt(linha, 7).toString());
                    f.setDt_nasc(tbprincipal.getValueAt(linha, 8).toString());
                    ca.setId((int) tbprincipal.getValueAt(linha, 9));
                    ca.setNome(tbprincipal.getValueAt(linha, 10).toString());
                    ca.setSalario((double) tbprincipal.getValueAt(linha, 11));
                    f.setCargo(ca);
                    f.setCtps(tbprincipal.getValueAt(linha, 12).toString());
                    f.setSerie(tbprincipal.getValueAt(linha, 13).toString());
                    f.setRg(tbprincipal.getValueAt(linha, 14).toString());
                    f.setCpf(tbprincipal.getValueAt(linha, 15).toString());
                                            
                        stmt = con.prepareStatement("select funcionário.cd_func,telefone_func.numero,telefone_func.cd_fone_func "
                                + "from Funcionário inner join telefone_func on Funcionário.cd_func = telefone_func.cd_func "
                                + "where Funcionário.cd_func = ?");
                        stmt.setInt(1, (int) tbprincipal.getValueAt(linha, 0));
                        rs = stmt.executeQuery();
                        
                        int i=0;
                        Telefone fone = new Telefone(); 
                        while(rs.next()){
                            fone.getIds()[i] = rs.getInt("cd_fone_func");
                            fone.getTelefones()[i] = rs.getInt("numero");
                            i+=1;
                        }
                    f.setFone(fone);
                    func.setVisible(true);
                    func.preencher_dados(f);
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, "Erro na busca! \n" + ex);
                        }
                break;
                case 4:
                    Acervo ac = new Acervo();
                    Autor a = new Autor();
                    Editora e = new Editora();
                    Genero g = new Genero();
                    FrLivro liv = new FrLivro();
                    ac.setId((int) tbprincipal.getValueAt(linha, 0));
                    ac.setNome(tbprincipal.getValueAt(linha, 1).toString());
                    ac.setValor((double) tbprincipal.getValueAt(linha, 2));
                    ac.setIsqn((int) tbprincipal.getValueAt(linha, 3));
                    ac.setQuatidade((int) tbprincipal.getValueAt(linha, 4));
                    a.setId((int) tbprincipal.getValueAt(linha, 5));
                    a.setNome(tbprincipal.getValueAt(linha, 6).toString());
                    e.setId((int) tbprincipal.getValueAt(linha, 7));
                    e.setNome(tbprincipal.getValueAt(linha, 8).toString());
                    g.setId((int) tbprincipal.getValueAt(linha, 9));
                    g.setNome(tbprincipal.getValueAt(linha, 10).toString());
                    ac.setAutor(a);
                    ac.setEditora(e);
                    ac.setGenero(g);
                    liv.setVisible(true);
                    liv.preencher_dados(ac);
                break;
                case 5:
                    Usuario p = new Usuario();
                    Funcionario fu = new Funcionario();
                    FrCadastroLogin log = new FrCadastroLogin();
                    p.setId((int) tbprincipal.getValueAt(linha, 0));
                    fu.setNome(tbprincipal.getValueAt(linha, 1).toString());
                    p.setFuncionario(fu);
                    log.setVisible(true);
                    log.preencher_dadosC(p);
                break;
                case 6:
                    Usuario c = new Usuario();
                    Funcionario fn = new Funcionario();
                    FrCadastroLogin lo = new FrCadastroLogin();
                    c.setId((int) tbprincipal.getValueAt(linha, 0));
                    fn.setNome(tbprincipal.getValueAt(linha, 1).toString());
                    c.setLogin(tbprincipal.getValueAt(linha, 2).toString());
                    c.setSenha(tbprincipal.getValueAt(linha, 3).toString());
                    c.setTipo_usuario((int) tbprincipal.getValueAt(linha, 4));
                    fn.setId((int) tbprincipal.getValueAt(linha, 5));
                    c.setFuncionario(fn);
                    lo.setVisible(true);
                    lo.preencher_dados(c);
                break;
                default:
                    JOptionPane.showMessageDialog(null, "Opção Invalida!!!");
            }
            
    }
    
    
    private void cons_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_funcActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbprincipal.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
                model.addColumn("ID");
                model.addColumn("Nome");
                model.addColumn("Logradouro");
                model.addColumn("Número");
                model.addColumn("Bairro");
                model.addColumn("Cidade");
                model.addColumn("UF");
                model.addColumn("cep");
                model.addColumn("Dt_nasc");
                model.addColumn("ID Cargo");
                model.addColumn("Cargo");
                model.addColumn("Salario");
                model.addColumn("CTPS");
                model.addColumn("Série");
                model.addColumn("RG");
                model.addColumn("CPF");
        FuncionarioDao pdao = new FuncionarioDao();
        
        for (Funcionario p : pdao.findAll()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getRua(),
                p.getNumero(),
                p.getBairro(),
                p.getCidade(),
                p.getUf(),
                p.getCep(),
                p.getDt_nasc(),
                p.getCargo().getId(),
                p.getCargo().getNome(),
                p.getCargo().getSalario(),
                p.getCtps(),
                p.getSerie(),
                p.getRg(),
                p.getCpf()
            });
            txt_form.setText("3");
            jPanel1.setVisible(true);

        }
    }//GEN-LAST:event_cons_funcActionPerformed

    private void func_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_func_mActionPerformed
        // TODO add your handling code here:
        new FrFuncionario().setVisible(true);
    }//GEN-LAST:event_func_mActionPerformed

    private void acervo_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acervo_mActionPerformed
        // TODO add your handling code here:
        new FrLivro().setVisible(true);
    }//GEN-LAST:event_acervo_mActionPerformed

    private void tbprincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbprincipalMouseClicked
        // TODO add your handling code here:
        tbprincipal.setDefaultEditor(Object.class, null);
        if(evt.getClickCount() == 2){
            select_jtable();
            jPanel1.setVisible(false);
            DefaultTableModel model = (DefaultTableModel)tbprincipal.getModel();
            JTable table = new JTable(model);
            model.setNumRows(0);
            model.setColumnCount(0);
        }
        
    }//GEN-LAST:event_tbprincipalMouseClicked

    private void cons_fisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_fisActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbprincipal.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
                model.addColumn("ID");
                model.addColumn("Nome");
                model.addColumn("Logradouro");
                model.addColumn("Número");
                model.addColumn("Bairro");
                model.addColumn("Cidade");
                model.addColumn("UF");
                model.addColumn("cep");
                model.addColumn("Dt_nasc");
                model.addColumn("RG");
                model.addColumn("CPF");
                model.addColumn("Status");
        ClienteFDao pdao = new ClienteFDao();
        
        for (Cliente p : pdao.findAll()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getRua(),
                p.getNumero(),
                p.getBairro(),
                p.getCidade(),
                p.getUf(),
                p.getCep(),
                p.getDt_nasc(),
                p.getRg(),
                p.getCpf(),
                p.getStatus()
            });
            txt_form.setText("1");
            jPanel1.setVisible(true);

        }
    }//GEN-LAST:event_cons_fisActionPerformed

    private void usuario_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuario_mActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbprincipal.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
                model.addColumn("ID");
                model.addColumn("Nome");
                model.addColumn("Logradouro");
                model.addColumn("Número");
                model.addColumn("Bairro");
                model.addColumn("Cidade");
                model.addColumn("UF");
                model.addColumn("cep");
                model.addColumn("Dt_nasc");
                model.addColumn("Cargo");
                model.addColumn("CTPS");
                model.addColumn("Série");
        UsuarioDao pdao = new UsuarioDao();
        
        for (Funcionario p : pdao.findAll_cad()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getRua(),
                p.getNumero(),
                p.getBairro(),
                p.getCidade(),
                p.getUf(),
                p.getCep(),
                p.getDt_nasc(),
                p.getCargo().getNome(),
                p.getCtps(),
                p.getSerie()
            });
            txt_form.setText("5");
            jPanel1.setVisible(true);

        }
    }//GEN-LAST:event_usuario_mActionPerformed

    private void cons_jurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_jurActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbprincipal.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
                model.addColumn("ID");
                model.addColumn("Nome");
                model.addColumn("Logradouro");
                model.addColumn("Número");
                model.addColumn("Bairro");
                model.addColumn("Cidade");
                model.addColumn("UF");
                model.addColumn("cep");
                model.addColumn("Razão Social");
                model.addColumn("CNPJ");
                model.addColumn("Status");
        ClienteJDao pdao = new ClienteJDao();
        
        for (Cliente p : pdao.findAll()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getRua(),
                p.getNumero(),
                p.getBairro(),
                p.getCidade(),
                p.getUf(),
                p.getCep(),
                p.getRazao_s(),
                p.getCnpj(),
                p.getStatus()
            });
            txt_form.setText("2");
            jPanel1.setVisible(true);

        }
    }//GEN-LAST:event_cons_jurActionPerformed

    private void cons_acervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cons_acervoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbprincipal.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
                model.addColumn("ID");
                model.addColumn("Nome Filme");
                model.addColumn("Valor Unit");
                model.addColumn("ISQN");
                model.addColumn("Estoque");
                model.addColumn("ID Autor");
                model.addColumn("Autor");
                model.addColumn("ID Editora");
                model.addColumn("Editora");
                model.addColumn("ID Genero");
                model.addColumn("Genero");
        AcervoDao pdao = new AcervoDao();
        
        for (Acervo p : pdao.findAll()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getValor(),
                p.getIsqn(),
                p.getQuatidade(),
                p.getAutor().getId(),
                p.getAutor().getNome(),
                p.getEditora().getId(),
                p.getEditora().getNome(),
                p.getGenero().getId(),
                p.getGenero().getNome(),
            });
            txt_form.setText("4");
            jPanel1.setVisible(true);

        }
    }//GEN-LAST:event_cons_acervoActionPerformed

    private void UsuarioC_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioC_mActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbprincipal.getModel();
                model.setNumRows(0);
                model.setColumnCount(0);
                model.addColumn("ID");
                model.addColumn("Nome");
                model.addColumn("Nome de Usuário");
                model.addColumn("Senha");
                model.addColumn("Tipo de Usuário");
                model.addColumn("ID Funcionário");
        UsuarioDao pdao = new UsuarioDao();
        
        for (Usuario p : pdao.findAll_con()) {
            model.addRow(new Object[]{
                p.getId(),
                p.getFuncionario().getNome(),
                p.getLogin(),
                p.getSenha().hashCode(),
                p.getTipo_usuario(),
                p.getFuncionario().getId()
            });
            txt_form.setText("6");
            jPanel1.setVisible(true);

        }
    }//GEN-LAST:event_UsuarioC_mActionPerformed

    private void atualizacao_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizacao_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizacao_mActionPerformed

    private void Emprestimo_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emprestimo_mActionPerformed
        // TODO add your handling code here:
        FrEmprestimoCliente e = new FrEmprestimoCliente();
        Usuario u = new Usuario();
        u.setId(id_usuario);
        u.setLogin(nm_usuario);
        e.setVisible(true);
        e.Retorna_usuario(u);
        
    }//GEN-LAST:event_Emprestimo_mActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "A desenvolver!");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
               
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Emprestimo_m;
    private javax.swing.JMenu Pedido_m;
    private javax.swing.JMenuItem UsuarioC_m;
    private javax.swing.JMenuItem acervo_m;
    private javax.swing.JMenuItem atualizacao_m;
    private javax.swing.JMenuItem cliente_m;
    private javax.swing.JMenuItem config_m;
    private javax.swing.JMenuItem cons_acervo;
    private javax.swing.JMenuItem cons_fis;
    private javax.swing.JMenuItem cons_func;
    private javax.swing.JMenuItem cons_jur;
    private javax.swing.JMenuItem func_m;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu rel_m;
    private javax.swing.JMenuItem sair_m;
    private javax.swing.JTable tbprincipal;
    private javax.swing.JTextField text_t;
    private javax.swing.JTextField text_t1;
    private javax.swing.JLabel tipo_usuariolb;
    private javax.swing.JTextField txt_form;
    private javax.swing.JMenuItem usuario_m;
    // End of variables declaration//GEN-END:variables

}
